/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLCH.UI;

import QLCH.Dao.ChiTietHoaDonDao;
import QLCH.Utils.Masterfrom;
import QLCH.Dao.GiamGiaDao;
import QLCH.Dao.HoaDonDao;
import QLCH.Dao.KhachHangDao;
import QLCH.Dao.LoaiSanPhamDao;
import QLCH.Dao.SanPhamDao;
import QLCH.Entity.ChiTietHoaDon;
import QLCH.Entity.GiamGia;
import QLCH.Entity.HoaDon;
import QLCH.Entity.KhachHang;
import QLCH.Entity.LoaiSanPham;
import QLCH.Entity.SanPham;
import QLCH.Utils.MessageBoxQLCH;
import QLCH.Utils.XImageQLCH;
import java.awt.Color;
import java.awt.Font;
import java.awt.print.PrinterException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AD
 */
public class BanHangJPanel extends Masterfrom {

    public BanHangJPanel() {
        initComponents();
        init();

        tblGioHang.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 13));
        tblGioHang.getTableHeader().setBackground(new Color(24, 71, 133));
        tblGioHang.getTableHeader().setForeground(new Color(255, 255, 255));

        tblLoaiSanPham.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 13));
        tblLoaiSanPham.getTableHeader().setBackground(new Color(24, 71, 133));
        tblLoaiSanPham.getTableHeader().setForeground(new Color(255, 255, 255));
        tblGioHang.setComponentPopupMenu(pmnChiTietHoaDon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmnChiTietHoaDon = new javax.swing.JPopupMenu();
        mnSua = new javax.swing.JMenuItem();
        mnXoa = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        cboLoaiSanPham = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lblAnh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoaiSanPham = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtChiTiet = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        pnlDienThongTinHoaDon = new javax.swing.JPanel();
        pnlThongtinKH = new javax.swing.JPanel();
        txtTimKhachHang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnTimKhachHang = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMaKhachHang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHoVaTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDiem = new javax.swing.JTextField();
        btnThemmoi = new javax.swing.JButton();
        cboKhachHang = new javax.swing.JComboBox<>();
        pnlThongtinTT = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTongTienHoaDon = new javax.swing.JTextField();
        txtPhanTram = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSoTienThanhToan = new javax.swing.JTextField();
        txtSoHoaDon = new javax.swing.JTextField();
        cboGiamgia = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtTienKhachDua = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTienThua = new javax.swing.JTextField();
        btnThanhToan = new javax.swing.JButton();
        btnInHoaDon = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnThemGioHang = new javax.swing.JButton();
        lblthongbao = new javax.swing.JLabel();
        btnXemHoaDon = new javax.swing.JButton();

        mnSua.setText("SuaThongTin");
        mnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSuaActionPerformed(evt);
            }
        });
        pmnChiTietHoaDon.add(mnSua);

        mnXoa.setText("XoaSanPham");
        mnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnXoaActionPerformed(evt);
            }
        });
        pmnChiTietHoaDon.add(mnXoa);

        setBackground(new Color (0, 0, 0, 0));

        jPanel1.setBackground(new Color (0, 0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SẢN PHẨM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new Color (33, 21, 81))); // NOI18N

        cboLoaiSanPham.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboLoaiSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất Cả" }));
        cboLoaiSanPham.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new Color (24, 71, 133)));
        cboLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiSanPhamActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new Color (16,54,103));
        jLabel1.setText("LOẠI SẢN PHẨM");

        lblAnh.setBackground(new java.awt.Color(255, 255, 255));
        lblAnh.setMaximumSize(new java.awt.Dimension(40, 40));

        tblLoaiSanPham.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        tblLoaiSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaSP", "TenSP", "Gia", "TrangThai", "Anh", "MaLoai", "SoLuong"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoaiSanPham.setRowHeight(23);
        tblLoaiSanPham.setSelectionBackground(new Color (24, 116, 180) );
        tblLoaiSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoaiSanPham);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboLoaiSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new Color (0, 0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BẢN IN HÓA ĐƠN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new Color (33, 21, 81))); // NOI18N

        txtChiTiet.setColumns(20);
        txtChiTiet.setRows(5);
        txtChiTiet.setEnabled(false);
        jScrollPane3.setViewportView(txtChiTiet);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new Color (0, 0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH SÁCH HÓA ĐƠN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new Color (33, 21, 81))); // NOI18N

        tblGioHang.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TT", "TenSP", "Gia", "SoLuong", "Thanh Tien"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGioHang.setRowHeight(23);
        tblGioHang.setSelectionBackground(new Color (24, 116, 180) );
        tblGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGioHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblGioHang);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(442, 442, 442))
        );

        pnlDienThongTinHoaDon.setBackground(new Color(0,0,0,0));

        pnlThongtinKH.setBackground(new Color (0, 0, 0, 0));
        pnlThongtinKH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTimKhachHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new Color (16,54,103));
        jLabel2.setText("THÔNG TIN KHÁCH HÀNG");

        btnTimKhachHang.setBackground(new Color (24, 71, 133));
        btnTimKhachHang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTimKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKhachHang.setText("Tìm");
        btnTimKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKhachHangActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel3.setForeground(new Color (16,54,103));
        jLabel3.setText("MaKH ");

        txtMaKhachHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel4.setForeground(new Color (16,54,103));
        jLabel4.setText("SDT ");

        txtHoVaTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel5.setForeground(new Color (16,54,103));
        jLabel5.setText("Họ Và Tên");

        txtSoDienThoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel6.setForeground(new Color (16,54,103));
        jLabel6.setText("Điểm ");

        txtDiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemActionPerformed(evt);
            }
        });

        btnThemmoi.setBackground(new Color (24, 71, 133));
        btnThemmoi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemmoi.setForeground(new java.awt.Color(255, 255, 255));
        btnThemmoi.setText("THÊM MỚI");
        btnThemmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemmoiActionPerformed(evt);
            }
        });

        cboKhachHang.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new Color (24, 71, 133)));
        cboKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKhachHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThongtinKHLayout = new javax.swing.GroupLayout(pnlThongtinKH);
        pnlThongtinKH.setLayout(pnlThongtinKHLayout);
        pnlThongtinKHLayout.setHorizontalGroup(
            pnlThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinKHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiem)
                    .addComponent(txtSoDienThoai)
                    .addComponent(txtHoVaTen)
                    .addComponent(txtMaKhachHang)
                    .addGroup(pnlThongtinKHLayout.createSequentialGroup()
                        .addGroup(pnlThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cboKhachHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongtinKHLayout.createSequentialGroup()
                        .addGroup(pnlThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTimKhachHang)
                            .addGroup(pnlThongtinKHLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnThemmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addComponent(btnTimKhachHang)))
                .addContainerGap())
        );
        pnlThongtinKHLayout.setVerticalGroup(
            pnlThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(cboKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlThongtinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnThemmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlThongtinTT.setBackground(new Color (0, 0, 0, 0));
        pnlThongtinTT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setForeground(new Color (16,54,103));
        jLabel7.setText("THÔNG TIN THANH TOÁN");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel8.setForeground(new Color (16,54,103));
        jLabel8.setText("Tổng Tiền Hóa Đơn");

        txtTongTienHoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTongTienHoaDon.setText("0");
        txtTongTienHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTongTienHoaDonMouseEntered(evt);
            }
        });
        txtTongTienHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienHoaDonActionPerformed(evt);
            }
        });

        txtPhanTram.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPhanTram.setText("0");
        txtPhanTram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhanTramActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel9.setForeground(new Color (16,54,103));
        jLabel9.setText("Phần Trăm Giảm Giá");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel10.setForeground(new Color (16,54,103));
        jLabel10.setText("Số Tiền Thanh Toán:");

        txtSoTienThanhToan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSoTienThanhToan.setText("0");

        txtSoHoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cboGiamgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGiamgiaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("%");

        txtTienKhachDua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTienKhachDua.setText("0");

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel12.setForeground(new Color (16,54,103));
        jLabel12.setText("SHD");

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel13.setForeground(new Color (16,54,103));
        jLabel13.setText("Tiền khách đưa");

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel14.setForeground(new Color (16,54,103));
        jLabel14.setText("Tiền thừa");

        txtTienThua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTienThua.setText("0");

        javax.swing.GroupLayout pnlThongtinTTLayout = new javax.swing.GroupLayout(pnlThongtinTT);
        pnlThongtinTT.setLayout(pnlThongtinTTLayout);
        pnlThongtinTTLayout.setHorizontalGroup(
            pnlThongtinTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinTTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlThongtinTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addGroup(pnlThongtinTTLayout.createSequentialGroup()
                        .addComponent(txtPhanTram, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(pnlThongtinTTLayout.createSequentialGroup()
                        .addGroup(pnlThongtinTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(pnlThongtinTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTienThua, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtTienKhachDua)))
                    .addGroup(pnlThongtinTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cboGiamgia, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlThongtinTTLayout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtSoHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                        .addComponent(txtSoTienThanhToan, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTongTienHoaDon, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );
        pnlThongtinTTLayout.setVerticalGroup(
            pnlThongtinTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongtinTTLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTongTienHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongtinTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhanTram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSoTienThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(pnlThongtinTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(cboGiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlThongtinTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlThongtinTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        btnThanhToan.setBackground(new Color (24, 71, 133));
        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-get-cash-30.png"))); // NOI18N
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnInHoaDon.setBackground(new Color (24, 71, 133));
        btnInHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-print-26.png"))); // NOI18N
        btnInHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInHoaDonActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new Color (24, 71, 133));
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-delete-document-30.png"))); // NOI18N
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnThemGioHang.setBackground(new Color (24, 71, 133));
        btnThemGioHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemGioHang.setForeground(new java.awt.Color(255, 255, 255));
        btnThemGioHang.setText("Thêm sản vào hóa đơn");
        btnThemGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemGioHangActionPerformed(evt);
            }
        });

        lblthongbao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnXemHoaDon.setBackground(new Color (24, 71, 133));
        btnXemHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-add-new-32.png"))); // NOI18N
        btnXemHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDienThongTinHoaDonLayout = new javax.swing.GroupLayout(pnlDienThongTinHoaDon);
        pnlDienThongTinHoaDon.setLayout(pnlDienThongTinHoaDonLayout);
        pnlDienThongTinHoaDonLayout.setHorizontalGroup(
            pnlDienThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDienThongTinHoaDonLayout.createSequentialGroup()
                .addGroup(pnlDienThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDienThongTinHoaDonLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnThemGioHang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDienThongTinHoaDonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlThongtinKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlDienThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDienThongTinHoaDonLayout.createSequentialGroup()
                        .addComponent(pnlThongtinTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDienThongTinHoaDonLayout.createSequentialGroup()
                        .addComponent(lblthongbao, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))))
            .addGroup(pnlDienThongTinHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDienThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDienThongTinHoaDonLayout.createSequentialGroup()
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDienThongTinHoaDonLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(btnXemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDienThongTinHoaDonLayout.setVerticalGroup(
            pnlDienThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDienThongTinHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDienThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblthongbao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDienThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlThongtinKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlThongtinTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDienThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnXemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDienThongTinHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDienThongTinHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiSanPhamActionPerformed
        // TODO add your handling code here:
        chonCombox();
    }//GEN-LAST:event_cboLoaiSanPhamActionPerformed

    private static String SoLuongMua, Anh;
    private void tblLoaiSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiSanPhamMouseClicked
        // TODO add your handling code here:
        int id = tblLoaiSanPham.rowAtPoint(evt.getPoint());
        layMaSanPham(id);
        soco = Integer.parseInt(tblLoaiSanPham.getValueAt(id, 6).toString());
        if(evt.getClickCount() >= 2){
            nhapsoluong();
        }
//        //hien form nhap so luong
//        if (evt.getClickCount() == 3) {
//            FormNhapSoLuongSanPham();
//        }
    }//GEN-LAST:event_tblLoaiSanPhamMouseClicked

    private void tblGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGioHangMouseClicked
            
    }//GEN-LAST:event_tblGioHangMouseClicked

    private void btnTimKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKhachHangActionPerformed
        fillThongTinKhachHang();
    }//GEN-LAST:event_btnTimKhachHangActionPerformed

    private void txtDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemActionPerformed

    private void btnThemmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemmoiActionPerformed
        insertKhachHang();
    }//GEN-LAST:event_btnThemmoiActionPerformed

    private void cboKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKhachHangActionPerformed
        // TODO add your handling code here:
        chonKhachHang();
    }//GEN-LAST:event_cboKhachHangActionPerformed

    private void txtTongTienHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTongTienHoaDonMouseEntered
        //fillcomboxGiamGia();
    }//GEN-LAST:event_txtTongTienHoaDonMouseEntered

    private void txtTongTienHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienHoaDonActionPerformed

    private void txtPhanTramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhanTramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhanTramActionPerformed

    private void cboGiamgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGiamgiaActionPerformed
        TinhTienPhanTram();
    }//GEN-LAST:event_cboGiamgiaActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        TinhTien();
        //xem();
        fillTableSanPham();
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnInHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInHoaDonActionPerformed
        try {
            // TODO add your handling code here:
            txtChiTiet.print();
        } catch (PrinterException ex) {
            Logger.getLogger(BanHangJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInHoaDonActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        ResetHoaDon();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnThemGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemGioHangActionPerformed
        fillcomboxGiamGia();
    }//GEN-LAST:event_btnThemGioHangActionPerformed

    private void mnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSuaActionPerformed
        // TODO add your handling code here:
        suaSanPhanGioHang();
    }//GEN-LAST:event_mnSuaActionPerformed

    private void mnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnXoaActionPerformed
        // TODO add your handling code here:
        xoaSanPhamGioHang();
    }//GEN-LAST:event_mnXoaActionPerformed

    private void btnXemHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemHoaDonActionPerformed
        xem();
    }//GEN-LAST:event_btnXemHoaDonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnInHoaDon;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemGioHang;
    private javax.swing.JButton btnThemmoi;
    private javax.swing.JButton btnTimKhachHang;
    private javax.swing.JButton btnXemHoaDon;
    private javax.swing.JComboBox<String> cboGiamgia;
    private javax.swing.JComboBox<String> cboKhachHang;
    private javax.swing.JComboBox<String> cboLoaiSanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblthongbao;
    private javax.swing.JMenuItem mnSua;
    private javax.swing.JMenuItem mnXoa;
    private javax.swing.JPopupMenu pmnChiTietHoaDon;
    private javax.swing.JPanel pnlDienThongTinHoaDon;
    private javax.swing.JPanel pnlThongtinKH;
    private javax.swing.JPanel pnlThongtinTT;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTable tblLoaiSanPham;
    private javax.swing.JTextArea txtChiTiet;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtHoVaTen;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtPhanTram;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtSoHoaDon;
    private javax.swing.JTextField txtSoTienThanhToan;
    private javax.swing.JTextField txtTienKhachDua;
    private javax.swing.JTextField txtTienThua;
    private javax.swing.JTextField txtTimKhachHang;
    private javax.swing.JTextField txtTongTienHoaDon;
    // End of variables declaration//GEN-END:variables

    KhachHangDao khDao = new KhachHangDao();
    SanPhamDao bhd = new SanPhamDao();
    LoaiSanPhamDao lspd = new LoaiSanPhamDao();
    private int soco;
    SanPhamDao spd = new SanPhamDao();
    HoaDonDao hdd = new HoaDonDao();
    ChiTietHoaDonDao cthdd = new ChiTietHoaDonDao();
    protected JRootPane rootPane;

    private void init() {
//        setLocationRelativeTo(null);
        fillComBoxLoaiSanPham();
        fillComBoxKhachHang();
//fillTableSanPham();
    }

    private void fillComBoxLoaiSanPham() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLoaiSanPham.getModel();
        model.removeAllElements();
        List<LoaiSanPham> list = lspd.selectAll();
        for (LoaiSanPham lsp : list) {
            model.addElement(lsp);
        }
    }

    private void fillTableSanPham() {
        DefaultTableModel model = (DefaultTableModel) tblLoaiSanPham.getModel();
        model.setRowCount(0);
        try {
            LoaiSanPham lsp = (LoaiSanPham) cboLoaiSanPham.getSelectedItem();
            List<SanPham> list = bhd.selectBySanPham(lsp.getMaLoaiSP());
//            List<SanPham> list = spd.selectAll();
            for (SanPham sp : list) {
                Object[] row = {
                    sp.getMaSP(),
                    sp.getTenSP(),
                    sp.getGia(),
                    sp.getTrangThai(),
                    sp.getAnh(),
                    sp.getMaLoai(),
                    sp.getSoLuong()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MessageBoxQLCH.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    private void chonCombox() {
        LoaiSanPham lsp = (LoaiSanPham) cboLoaiSanPham.getSelectedItem();
        if (lsp != null) {
            fillTableSanPham();
        }
    }

    private void setForm(SanPham sp) {
        if (sp.getAnh() != null) {
            lblAnh.setToolTipText(sp.getAnh());
            lblAnh.setIcon(XImageQLCH.read(sp.getAnh()));
        }
    }

    private SanPham getForm() {
        SanPham cd = new SanPham();
        cd.setAnh(lblAnh.getToolTipText());
        return cd;
    }

    public void LoaiDataChiTietHoaDon(JTable tbl, SanPham sp, String SoLuongMua, String Anh) {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();

        String image = sp.getAnh();
        JLabel lblff = new JLabel();
        ImageIcon imageIcon = new ImageIcon(image);
        lblff.setIcon(imageIcon);

        Object[] obj = new Object[5];
        // thu tu
//        obj[0] = model.getRowCount()+1;
        obj[0] = sp.getMaSP();
        // ten san pham
        obj[1] = sp.getTenSP();
        // gia
        obj[2] = sp.getGia();
        // soluongmua
        obj[3] = SoLuongMua;
        // thanh tien
        obj[4] = Float.parseFloat(SoLuongMua) * sp.getGia();
        model.addRow(obj);
    }

    public static String TinhTongTien(JTable tbl) {

        double tongtien = 0;
        for (int i = 0; i < tbl.getRowCount(); i++) {
            tongtien += Double.parseDouble(tbl.getValueAt(i, 4).toString());
        }

        return String.valueOf(tongtien);
    }

    GiamGiaDao ggDao = new GiamGiaDao();

    void fillcomboxGiamGia() {
        txtSoHoaDon.setText(hdd.TaoMaHoaDon());
        DefaultComboBoxModel cboModel = (DefaultComboBoxModel) cboGiamgia.getModel();
        cboModel.removeAllElements();
        float gia = Float.parseFloat(txtTongTienHoaDon.getText());
        List<GiamGia> list = ggDao.selectAll();
        for (GiamGia gg : list) {
            if (gia > gg.getDieuKien()) {
                cboModel.addElement(gg);
            }
        }
    }

    void TinhTienPhanTram() {
        try {
            GiamGia giamgia = (GiamGia) cboGiamgia.getSelectedItem();
            if (giamgia != null) {
                List<GiamGia> list = ggDao.selectMaGG(giamgia.getMaGG());
                System.out.println("" + list);
                for (GiamGia gg : list) {
                    int phantram = gg.getGiaTri();
                    txtPhanTram.setText(String.valueOf(phantram));
                    float tongtien = Float.parseFloat(txtTongTienHoaDon.getText());
                    float thanhtien = tongtien - (tongtien * phantram) / 100;
                    System.out.println("Phantram: " + phantram + " Thanh tien: " + thanhtien);
                    txtSoTienThanhToan.setText(String.valueOf(thanhtien));
                }
            }
        } catch (Exception e) {
            MessageBoxQLCH.alert(this, "Lỗi tính phần trăm");
        }
    }

    void TinhTien() {
        float tienkhanhdua = Float.parseFloat(txtTienKhachDua.getText());
        float thanhtien = Float.parseFloat(txtSoTienThanhToan.getText());
        if (tienkhanhdua == thanhtien) {
            txtTienThua.setText("0");
        } else if (tienkhanhdua > thanhtien) {
            float tienthua = tienkhanhdua - thanhtien;
            txtTienThua.setText(String.valueOf(tienthua));
            // luu hoa don
            HoaDon hd = new HoaDon();
            String soHoa = hdd.TaoMaHoaDon();
            try {

                hd.setMaHD(soHoa);

                hd.setMaKH(txtMaKhachHang.getText());
                hd.setMaNV((LoginJDialog.nv.getMaNV()));
                //hd.setMaNV("NV01");
                //lay maNV dang dang nhap
//            hd.setMaNV(AuthRoleQLCH.user.getMaNV());
                hd.setNgayBan(new Date());
                hdd.ThemHD(hd);

                lblthongbao.setText("ThanhToanThanhCong");
//            fillTableHoaDon();

                // xoa trang gioi hang
//            DefaultTableModel model = (DefaultTableModel) tblGioHang.getModel();
//            model.setRowCount(0);
            } catch (Exception e) {
                e.printStackTrace();
                lblthongbao.setText("ThanhToanThatBai");
            }
            // luu cthoado
            ThemCTHoaDon(tblGioHang, soHoa);
        } else {
            MessageBoxQLCH.alert(this, "Tiền không đủ để thực hiện thanh toán");
        }

    }

    void setForm(KhachHang kh) {
        txtMaKhachHang.setText(kh.getMaKH());
        txtHoVaTen.setText(kh.getTenKH());
        txtSoDienThoai.setText(kh.getSdt());
        txtDiem.setText(String.valueOf(kh.getDiem()));
    }

    KhachHang getFormKH() {
        KhachHang kh = new KhachHang();
        kh.setMaKH(txtMaKhachHang.getText());
        kh.setTenKH(txtHoVaTen.getText());
        kh.setSdt(txtSoDienThoai.getText());
        kh.setDiem(Float.parseFloat(txtDiem.getText()));
        return kh;
    }

    void fillThongTinKhachHang() {
        try {
            String maKH = txtTimKhachHang.getText();
            KhachHang kh = khDao.SelectbyID(maKH);
            System.out.println("" + maKH + " " + kh);
            if (kh != null) {
                this.setForm(kh);
            } else {
                MessageBoxQLCH.alert(this, "Khách hàng chưa có trong danh sách");
                this.setForm(new KhachHang());
            }
        } catch (Exception e) {
            MessageBoxQLCH.alert(this, "Lỗi tìm kiếm khách hàng");
            e.printStackTrace();
        }
    }

    void insertKhachHang() {
        try {
            String togntien = txtTongTienHoaDon.getText();
            if (Float.parseFloat(togntien) < 80000) {
                txtDiem.setText("10");
            }
            KhachHang khModel = getFormKH();
            khDao.insert(khModel);
            fillComBoxKhachHang();
            MessageBoxQLCH.alert(this, "Thêm khách hàng thành công");
        } catch (Exception e) {
            MessageBoxQLCH.alert(this, "Lỗi thêm khách hàng");
            e.printStackTrace();
        }
    }

    void fillComBoxKhachHang() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboKhachHang.getModel();
        model.removeAllElements();
        List<KhachHang> list = khDao.selectAll();
        for (KhachHang lsp : list) {
            model.addElement(lsp);
        }
    }

    private void chonKhachHang() {
        KhachHang lsp = (KhachHang) cboKhachHang.getSelectedItem();
        if (lsp != null) {
            setForm(lsp);
        }
    }

    private void xem() {
        //gioithieu
        txtChiTiet.setText(txtChiTiet.getText() + "\t\t" + "PHIẾU MUA HÀNG" + "\n");
        txtChiTiet.setText(txtChiTiet.getText() + "Số Hóa Đơn: " + txtSoHoaDon.getText() + "\n");
        txtChiTiet.setText(txtChiTiet.getText() + "TÊN QUÁN : YUMMY JAVA" + "\n");
        txtChiTiet.setText(txtChiTiet.getText() + "DIA CHI:  87/2 Tân thới hiệp 06, P.Tân Thới Hiệp, Q12, TP HCM\n");
        txtChiTiet.setText(txtChiTiet.getText() + "SO DIEN THOAI: 039854245 \n");
        txtChiTiet.setText(txtChiTiet.getText() + "CONTER: \n");
        txtChiTiet.setText(txtChiTiet.getText() + "Tên Khách Hàng : " + "\t" + txtHoVaTen.getText() + "\t" + "Số Điện Thoại: " + txtSoDienThoai.getText() + "\n");
        txtChiTiet.setText(txtChiTiet.getText() + "---------------------------------------------------------------------------------------------------------------------------------------------- \n");
        txtChiTiet.setText(txtChiTiet.getText() + "Tên Sản Phẩm\tSố Lượng\tGiá\t Thành Tiền\n");
        txtChiTiet.setText(txtChiTiet.getText() + "---------------------------------------------------------------------------------------------------------------------------------------------- \n");

        for (int i = 0; i < tblGioHang.getRowCount(); i++) {
            String tenSP = tblGioHang.getValueAt(i, 1).toString();
            String Gia = tblGioHang.getValueAt(i, 3).toString();
            String soLuong = tblGioHang.getValueAt(i, 2).toString();
            String tienSp = tblGioHang.getValueAt(i, 4).toString();

            txtChiTiet.setText(txtChiTiet.getText() + tenSP + "\t" + "|" + Gia + "\t" + "|" + soLuong + "\t" + "|" + tienSp + "\n");

        }
        txtChiTiet.setText(txtChiTiet.getText() + "--------------------------------------------------------------------------------------------------------------------------------------------\n");

        txtChiTiet.setText(txtChiTiet.getText() + "Thanh Toán: " + "\t\t\t\t\t" + TinhTongTien(tblGioHang) + " đ" + "\n");
        txtChiTiet.setText(txtChiTiet.getText() + "--------------------------------------------------------------------------------------------------------------------------------------------\n");

        txtChiTiet.setText(txtChiTiet.getText() + "Phần Trăm Giảm Giá : " + "\t\t\t\t" + txtPhanTram.getText() + " %" + "\n\n");
        txtChiTiet.setText(txtChiTiet.getText() + "Số Cần Phải Trả : " + "\t\t\t\t" + txtSoTienThanhToan.getText() + " đ" + "\n\n");
        txtChiTiet.setText(txtChiTiet.getText() + "Số tiền dư: " + "\t\t\t\t\t" + txtTienThua.getText() + " đ" + "\n\n");

        txtChiTiet.setText(txtChiTiet.getText() + "-------------------------------------------------------------------------------------------------------------------------------------------- \n");
        txtChiTiet.setText(txtChiTiet.getText() + "                                         -----------------------Cảm ơn quý khách------------------------ \n");
        txtChiTiet.setText(txtChiTiet.getText() + "-------------------------------------------------------------------------------------------------------------------------------------------- \n");

//        DefaultTableModel model = (DefaultTableModel) tblGioHang.getModel();
//        int nrow = model.getRowCount(), ncol = model.getColumnCount();
//        
//        Object[][] tableDate = new Object[nrow][ncol];
//        
//        for (int i = 0; i < nrow; i++) {
//            for (int j = 0; j < ncol; j++) {
//                tableDate [i][j] = model.getValueAt(i, j);
//                txtChiTiet.append(tableDate[i][j]+ "\t\t");
//            }
//            txtChiTiet.append("\n");
//        }
    }

    public void ThemCTHoaDon(JTable tbl, String SoHoaDon) {
        HoaDon hd = hdd.layHoaDonTheoSoHoaDon(SoHoaDon);
        String mahd = hd.getMaHD();

        for (int i = 0; i < tbl.getRowCount(); i++) {
            ChiTietHoaDon cthd = new ChiTietHoaDon();

            cthd.setMaHD(SoHoaDon);
            cthd.setMaSP((String) tbl.getValueAt(i, 0));
            cthd.setSoLuong(Integer.parseInt((String) tbl.getValueAt(i, 3)));
            cthd.setTrangThai(lblthongbao.getText());
            cthd.setTongTien((Float) tbl.getValueAt(i, 4));
            cthd.setGia((Float) tbl.getValueAt(i, 2));

            cthdd.ThemCTHoaDon(cthd);
        }
    }
    
    void FormNhapSoLuongSanPham(){
        SoLuongMua = JOptionPane.showInputDialog(rootPane, "SoLuong", DISPOSE_ON_CLOSE);
        System.out.println("SL: " + SoLuongMua);
        String idSP = tblLoaiSanPham.getValueAt(tblLoaiSanPham.getSelectedRow(), 0).toString();
        SanPham sp = spd.GetSanPham(idSP);
        LoaiDataChiTietHoaDon(tblGioHang, sp, SoLuongMua, Anh);
        txtTongTienHoaDon.setText(TinhTongTien(tblGioHang));
    }
        
        
    @Override
    public void formRefresh() {
    }

    private void suaSanPhanGioHang() {
        int so = 1;
        int vitri = tblGioHang.getSelectedRow();
        SoLuongMua = tblGioHang.getValueAt(vitri, 3).toString();

        SoLuongMua = JOptionPane.showInputDialog(rootPane, "So luong mua", DISPOSE_ON_CLOSE);
        try {
            Integer.parseInt(SoLuongMua);
            if (SoLuongMua.isEmpty()) {
            so = Integer.parseInt(tblGioHang.getValueAt(vitri, 3).toString());
            }else if(Integer.parseInt(SoLuongMua) > soco || Integer.parseInt(SoLuongMua)<=0){
                JOptionPane.showMessageDialog(this, "Không đủ sản phẩm");
            }
            else{
                System.out.println("van thuc hien duoc");
                double thanhTien = Double.parseDouble(SoLuongMua) * Double.parseDouble(tblGioHang.getValueAt(vitri, 2).toString());
                tblGioHang.setValueAt(thanhTien, vitri, 4);
                txtTongTienHoaDon.setText(TinhTongTien(tblGioHang));
                
                tblGioHang.setValueAt(SoLuongMua, vitri, 3);
            }
        } catch (NumberFormatException e) {
            MessageBoxQLCH.alert(this, "Không đúng định dạng số");
        }      
    }

    private void xoaSanPhamGioHang() {
        DefaultTableModel tblModel = (DefaultTableModel) tblGioHang.getModel();

        int vitri = tblGioHang.getSelectedRow();
        if (vitri >= 0) {
            tblModel.removeRow(vitri);
            for (int i = 0; i < tblGioHang.getRowCount(); i++) {
                tblGioHang.setValueAt(i + 1, i, 1);// set lai so thu tu
            }
        }
        txtTongTienHoaDon.setText(TinhTongTien(tblGioHang));
    }

    private void layMaSanPham(int id) {
        String masv = tblLoaiSanPham.getValueAt(id, 0).toString();
        SanPham std = bhd.SelectbyID(masv);
        setForm(std);
    }
    
    private void nhapsoluong() {
        SoLuongMua = JOptionPane.showInputDialog(rootPane, "SoLuong", EXIT_ON_CLOSE);
        try {
            Integer.parseInt(SoLuongMua);
            // nhap rong
            if(SoLuongMua.equals("")){
                System.out.println("SL: "+ SoLuongMua);
                float i = 1;
                SoLuongMua = String.valueOf(i);
            }else if(Integer.parseInt(SoLuongMua) > soco || Integer.parseInt(SoLuongMua)<=0){
                JOptionPane.showMessageDialog(this, "Không đủ sản phẩm");      
            }else{
                System.out.println("SL: "+ SoLuongMua);
                String idSP = tblLoaiSanPham.getValueAt(tblLoaiSanPham.getSelectedRow(), 0).toString();
                SanPham sp = spd.GetSanPham(idSP);
                LoaiDataChiTietHoaDon(tblGioHang, sp, SoLuongMua, Anh);
                txtTongTienHoaDon.setText(TinhTongTien(tblGioHang));  
            }
        } catch (NumberFormatException e) {
            MessageBoxQLCH.alert(this, "Không đúng định dạng số");
        }    
        
    }

    private void ResetHoaDon() {
       txtPhanTram.setText("");
       txtSoTienThanhToan.setText("");
       //txtSoHoaDon.setText("");
       txtTienKhachDua.setText("");
       txtTienThua.setText("");
       txtChiTiet.setText("");
    }
}
