/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLCH.UI;

import QLCH.Utils.AuthRoleQLCH;
import QLCH.Utils.Masterfrom;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import static java.awt.image.ImageObserver.ALLBITS;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author AD
 */
public class FooterJPanel extends Masterfrom {

    /**
     * Creates new form FooterJPanel
     */
    public FooterJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1317, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private BufferedImage img, img2;

    int z = -100;
    int y = 35;
    int t = 219;
    int i = 35;
    int e = -60;
    int r = 15;
    int q = -650;
    int k = 5;

    public void paint(Graphics gp) {
        try {
            img = ImageIO.read(getClass().getResourceAsStream("/QLCH/Icon/icons8-who-30.png"));
            img2 = ImageIO.read(getClass().getResourceAsStream("/QLCH/Icon/MANAGEMENT-SERVICE.png"));
        } catch (IOException ex) {
            Logger.getLogger(HomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        super.paint(gp);
        Graphics2D g2d = (Graphics2D) gp;

        g2d.setColor(new Color(16, 78, 139));
        g2d.setFont(new Font("ALLBITS", ALLBITS, 15));

        if (AuthRoleQLCH.isLogin()) {
            g2d.drawString("Welcome: " + AuthRoleQLCH.user.getTenNV(), z, y);
        }
        if (!AuthRoleQLCH.isLogin()) {
            g2d.drawImage(img, e, r, null);
        }

        g2d.drawString("Welcome to Yummy JAVA", t, i);

        g2d.drawImage(img2, q, k, null);
        try {
            Thread.sleep(1);
            z += 2;
            t += 2;
            e += 2;
            q += 2;
            if (z > getWidth()) {
                z = -100;
            }
            if (t > getWidth()) {
                t = -100;
            }
            if (e > getWidth()) {
                e = -60;
            }
            if (q > getWidth()) {
                q = -200;
            }
            repaint();

        } catch (InterruptedException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

    }

    @Override
    public void formRefresh() {
    }
}
