/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLCH.UI;

import QLCH.Dao.GiamGiaDao;
import QLCH.Entity.GiamGia;
import QLCH.Utils.AuthRoleQLCH;
import QLCH.Utils.Masterfrom;
import QLCH.Utils.MessageBoxQLCH;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AD
 */
public class GiamGiaJPanel extends Masterfrom {

    /**
     * Creates new form GiamGiaJPanel
     */
    public GiamGiaJPanel() {
        initComponents();
        init();

        tblgiamgia.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 14));
        tblgiamgia.getTableHeader().setBackground(new Color(24, 71, 133));
        tblgiamgia.getTableHeader().setForeground(new Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEdit = new javax.swing.JPanel();
        txtDieuKien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtChietKhau = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtNgayBD = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmaGG = new javax.swing.JTextField();
        txtNgayKetThuc = new com.toedter.calendar.JDateChooser();
        txtTenGG = new javax.swing.JTextField();
        pnlButton = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        btnXoaTrang = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblgiamgia = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new Color (16,54,103));

        pnlEdit.setBackground(new Color (0, 0, 0, 0));

        txtDieuKien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDieuKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDieuKienActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new Color (16,54,103));
        jLabel4.setText("Chiết khấu giảm giá:");

        txtChietKhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("%");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new Color (16,54,103));
        jLabel7.setText("Mã NV:");

        txtMaNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });

        txtNgayBD.setToolTipText("");
        txtNgayBD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new Color (16,54,103));
        jLabel1.setText("Mã giảm giá:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new Color (16,54,103));
        jLabel2.setText("Tên giảm giá:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new Color (16,54,103));
        jLabel3.setText("Điều kiện giảm giá:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new Color (16,54,103));
        jLabel5.setText("Ngày bắt đầu:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new Color (16,54,103));
        jLabel6.setText("Ngày kết thúc:");

        txtmaGG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtmaGG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaGGActionPerformed(evt);
            }
        });

        txtNgayKetThuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTenGG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnlEditLayout = new javax.swing.GroupLayout(pnlEdit);
        pnlEdit.setLayout(pnlEditLayout);
        pnlEditLayout.setHorizontalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgayBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTenGG)
                    .addComponent(txtDieuKien)
                    .addGroup(pnlEditLayout.createSequentialGroup()
                        .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEditLayout.createSequentialGroup()
                                .addComponent(txtChietKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8))
                            .addComponent(txtmaGG, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(52, 52, 52))
        );
        pnlEditLayout.setVerticalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmaGG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenGG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDieuKien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtChietKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        btnXoa.setBackground(new Color (24, 71, 133) );
        btnXoa.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-remove-30.png"))); // NOI18N
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnXoaTrang.setBackground(new Color (24, 71, 133) );
        btnXoaTrang.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnXoaTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-broom-30.png"))); // NOI18N
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new Color (24, 71, 133) );
        btnCapNhat.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-update-30.png"))); // NOI18N
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnThem.setBackground(new Color (24, 71, 133) );
        btnThem.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-add-new-32.png"))); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonLayout = new javax.swing.GroupLayout(pnlButton);
        pnlButton.setLayout(pnlButtonLayout);
        pnlButtonLayout.setHorizontalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlButtonLayout.setVerticalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tblgiamgia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblgiamgia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã GG", "Tên GG", "Điều Kiện GG", "Chiết khấu", "Ngày bắt đầu", "Ngày kết thúc", "Mã NV"
            }
        ));
        tblgiamgia.setGridColor(new java.awt.Color(51, 153, 255));
        tblgiamgia.setRowHeight(23);
        tblgiamgia.setSelectionBackground(new Color (24, 116, 180) );
        tblgiamgia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblgiamgiaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblgiamgia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(pnlEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(44, Short.MAX_VALUE)
                        .addComponent(pnlEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDieuKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDieuKienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDieuKienActionPerformed

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void txtmaGGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaGGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaGGActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        update();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangActionPerformed
        clearForm();
    }//GEN-LAST:event_btnXoaTrangActionPerformed

    private void tblgiamgiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblgiamgiaMouseClicked
        this.row = tblgiamgia.rowAtPoint(evt.getPoint());
        edit();
    }//GEN-LAST:event_tblgiamgiaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaTrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlEdit;
    private javax.swing.JTable tblgiamgia;
    private javax.swing.JTextField txtChietKhau;
    private javax.swing.JTextField txtDieuKien;
    private javax.swing.JTextField txtMaNV;
    private com.toedter.calendar.JDateChooser txtNgayBD;
    private com.toedter.calendar.JDateChooser txtNgayKetThuc;
    private javax.swing.JTextField txtTenGG;
    private javax.swing.JTextField txtmaGG;
    // End of variables declaration//GEN-END:variables

    GiamGiaDao ggDao = new GiamGiaDao();
    int row = -1;

    private void init() {
//        this.setLocationRelativeTo(null);
        txtMaNV.setEditable(false);
        this.fillTable();
    }

    void fillTable() {
        DefaultTableModel tblModel = (DefaultTableModel) tblgiamgia.getModel();
        tblModel.setRowCount(0);
        try {
            List<GiamGia> list = ggDao.selectAll();
            for (GiamGia gg : list) {
                Object[] row = {gg.getMaGG(), gg.getTenGG(), "> " + gg.getDieuKien() + " đ", gg.getGiaTri() + " %", gg.getNgayBD(), gg.getNgayKT(), gg.getMaNV()};
                tblModel.addRow(row);
            }
        } catch (Exception e) {
            MessageBoxQLCH.alert(this, "Lỗi truy vấn bảng giảm giá");
            e.printStackTrace();
        }
    }

    void setForm(GiamGia gg) {
        txtmaGG.setText(gg.getMaGG());
        txtTenGG.setText(gg.getTenGG());
        txtDieuKien.setText(String.valueOf(gg.getDieuKien()));
        txtChietKhau.setText(String.valueOf(gg.getGiaTri()));
        txtNgayBD.setDate(gg.getNgayBD());
        txtNgayKetThuc.setDate(gg.getNgayKT());
        txtMaNV.setText(gg.getMaNV());
    }

    GiamGia getForm() {
        GiamGia gg = new GiamGia();
        gg.setMaGG(txtmaGG.getText());
        gg.setTenGG(txtTenGG.getText());
        gg.setDieuKien(Float.parseFloat(txtDieuKien.getText()));
        gg.setGiaTri(Integer.parseInt(txtChietKhau.getText()));
        gg.setNgayBD(txtNgayBD.getDate());
        gg.setNgayKT(txtNgayKetThuc.getDate());
        gg.setMaNV(AuthRoleQLCH.user.getMaNV());
        //gg.setMaNV(txtMaNV.getText());
        return gg;
    }

    void clearForm() {
        this.setForm(new GiamGia());
        txtMaNV.setText(AuthRoleQLCH.user.getMaNV());
        row = -1;
    }

    void edit() {
        try {
            String maGG = (String) tblgiamgia.getValueAt(row, 0);
            GiamGia gg = ggDao.SelectbyID(maGG);
            if (gg != null) {
                this.setForm(gg);
            }
        } catch (Exception e) {
            MessageBoxQLCH.alert(this, "Lỗi truy vấn edit");
            e.printStackTrace();
        }
    }

    void insert() {
        GiamGia ggModel = getForm();
        try {
            ggDao.insert(ggModel);
            this.fillTable();
            this.clearForm();
            MessageBoxQLCH.alert(this, "Thêm phiếu giảm giá thành công");
        } catch (Exception e) {
            MessageBoxQLCH.alert(this, "Lỗi thêm phiếu giảm giá");
            e.printStackTrace();
        }
    }

    void update() {
        GiamGia ggModel = getForm();
        try {
            ggDao.update(ggModel);
            this.fillTable();
            this.clearForm();
            MessageBoxQLCH.alert(this, "Cập nhật phiếu giảm giá thành công");
        } catch (Exception e) {
            MessageBoxQLCH.alert(this, "Lỗi cập nhật phiếu giảm giá");
            e.printStackTrace();
        }
    }

    void delete() {
        if (!AuthRoleQLCH.isManager()) {
            MessageBoxQLCH.alert(this, "Bạn không có quyền xóa hóa đơn");
        } else {
            if (MessageBoxQLCH.confirm(this, "Bạn muốn xóa phiếu giảm giá này")) {
                String maGG = txtmaGG.getText();
                try {
                    ggDao.delete(maGG);
                    this.clearForm();
                    this.fillTable();
                    MessageBoxQLCH.alert(this, "Xóa phiếu giảm giá thành công");
                } catch (Exception e) {
                    MessageBoxQLCH.alert(this, "Lỗi xóa phiếu giảm giá");
                    e.printStackTrace();
                }
            }
        }
    }

    @Override
    public void formRefresh() {
    }

}
