/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLCH.UI;

import QLCH.Utils.Masterfrom;
import QLCH.Dao.KhachHangDao;
import QLCH.Entity.KhachHang;
import QLCH.Utils.AuthRoleQLCH;
import QLCH.Utils.MessageBoxQLCH;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AD
 */
public class KhachHangJPanel extends Masterfrom {

    /**
     * Creates new form KhachHangJPanel
     */
    public KhachHangJPanel() {
        initComponents();
        init();

        tblKhachHang.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 14));
        tblKhachHang.getTableHeader().setBackground(new Color(24, 71, 133));
        tblKhachHang.getTableHeader().setForeground(new Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThietlapthongtinKhachhang = new javax.swing.JPanel();
        lblMaKH = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        lblTenKH = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        lblSoDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lblDiem = new javax.swing.JLabel();
        txtDiem = new javax.swing.JTextField();
        btnXoaTrang = new javax.swing.JButton();
        btnCapnhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        pnlTableTTKH = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        lblTimtenKH = new javax.swing.JLabel();

        setBackground(new Color (0, 0, 0, 0));
        setForeground(new Color (16,54,103));

        pnlThietlapthongtinKhachhang.setBackground(new Color (0, 0, 0, 0));
        pnlThietlapthongtinKhachhang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thiết lập thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 19), new Color (33, 21, 81))); // NOI18N

        lblMaKH.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblMaKH.setForeground(new Color (16,54,103));
        lblMaKH.setText("Mã khách hàng");

        txtMaKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblTenKH.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTenKH.setForeground(new Color (16,54,103));
        lblTenKH.setText("Tên Khách hàng");

        txtTenKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblSoDT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblSoDT.setForeground(new Color (16,54,103));
        lblSoDT.setText("Số điện thoại");

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        lblDiem.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblDiem.setForeground(new Color (16,54,103));
        lblDiem.setText("Điểm");

        txtDiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnXoaTrang.setBackground(new Color (24, 71, 133));
        btnXoaTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-broom-30.png"))); // NOI18N
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });

        btnCapnhat.setBackground(new Color (24, 71, 133));
        btnCapnhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-update-30.png"))); // NOI18N
        btnCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new Color (24, 71, 133));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-remove-30.png"))); // NOI18N
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThietlapthongtinKhachhangLayout = new javax.swing.GroupLayout(pnlThietlapthongtinKhachhang);
        pnlThietlapthongtinKhachhang.setLayout(pnlThietlapthongtinKhachhangLayout);
        pnlThietlapthongtinKhachhangLayout.setHorizontalGroup(
            pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThietlapthongtinKhachhangLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTenKH)
                    .addComponent(lblMaKH)
                    .addComponent(txtMaKH)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSoDT)
                    .addComponent(lblDiem)
                    .addComponent(txtSDT)
                    .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134)
                .addGroup(pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXoaTrang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCapnhat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        pnlThietlapthongtinKhachhangLayout.setVerticalGroup(
            pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThietlapthongtinKhachhangLayout.createSequentialGroup()
                .addGroup(pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThietlapthongtinKhachhangLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaKH)
                            .addComponent(lblSoDT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenKH)
                            .addComponent(lblDiem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlThietlapthongtinKhachhangLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnXoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnCapnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pnlTableTTKH.setBackground(new Color (0, 0, 0, 0));
        pnlTableTTKH.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 19), new Color (33, 21, 81))); // NOI18N

        tblKhachHang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma Khách hàng", "Tên khách hàng", "Số điện thoại", "Điểm"
            }
        ));
        tblKhachHang.setRowHeight(23);
        tblKhachHang.setSelectionBackground(new Color (24, 116, 180));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimKiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimKiemCaretUpdate(evt);
            }
        });
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new Color (24, 71, 133));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-search-30.png"))); // NOI18N
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        lblTimtenKH.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTimtenKH.setForeground(new Color (16,54,103) );
        lblTimtenKH.setText("Tên khách hàng");

        javax.swing.GroupLayout pnlTableTTKHLayout = new javax.swing.GroupLayout(pnlTableTTKH);
        pnlTableTTKH.setLayout(pnlTableTTKHLayout);
        pnlTableTTKHLayout.setHorizontalGroup(
            pnlTableTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableTTKHLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTimtenKH)
                .addGap(26, 26, 26)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
            .addGroup(pnlTableTTKHLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        pnlTableTTKHLayout.setVerticalGroup(
            pnlTableTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableTTKHLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlTableTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTableTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTimtenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlThietlapthongtinKhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTableTTKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(pnlThietlapthongtinKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(pnlTableTTKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangActionPerformed
        clearForm();
    }//GEN-LAST:event_btnXoaTrangActionPerformed

    private void btnCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatActionPerformed
        update();
    }//GEN-LAST:event_btnCapnhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        this.row = tblKhachHang.rowAtPoint(evt.getPoint());
        edit();
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        TimKiem();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
//        TimKiem();
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtTimKiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimKiemCaretUpdate
        // TODO add your handling code here:
//        TimKiem();
    }//GEN-LAST:event_txtTimKiemCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaTrang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiem;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JLabel lblSoDT;
    private javax.swing.JLabel lblTenKH;
    private javax.swing.JLabel lblTimtenKH;
    private javax.swing.JPanel pnlTableTTKH;
    private javax.swing.JPanel pnlThietlapthongtinKhachhang;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    KhachHangDao khDao = new KhachHangDao();
    int row = -1;

    private void init() {
//        this.setLocationRelativeTo(null);
        this.fillTable();
    }

    void fillTable() {
        DefaultTableModel tblModel = (DefaultTableModel) tblKhachHang.getModel();
        tblModel.setRowCount(0);
        try {
            String keyWord = txtTimKiem.getText();
            List<KhachHang> list = khDao.selectByKeyword(keyWord);
            for (KhachHang kh : list) {
                Object[] row = {kh.getMaKH(), kh.getTenKH(), kh.getSdt(), kh.getDiem()};
                tblModel.addRow(row);
            }
        } catch (Exception e) {
            MessageBoxQLCH.alert(this, "Lỗi truy vấn dữ liệu bảng");
            e.printStackTrace();
        }
    }

    void setForm(KhachHang kh) {
        txtMaKH.setText(kh.getMaKH());
        txtTenKH.setText(kh.getTenKH());
        txtSDT.setText(kh.getSdt());
        txtDiem.setText(String.valueOf(kh.getDiem()));
    }

    KhachHang getForm() {
        KhachHang kh = new KhachHang();
        kh.setMaKH(txtMaKH.getText());
        kh.setTenKH(txtTenKH.getText());
        kh.setSdt(txtSDT.getText());
        kh.setDiem(Float.parseFloat(txtDiem.getText()));
        return kh;
    }

    void clearForm() {
        this.setForm(new KhachHang());
        row = -1;
    }

    void edit() {
        try {
            String maKH = (String) tblKhachHang.getValueAt(row, 0);
            KhachHang kh = khDao.SelectbyID(maKH);
            if (kh != null) {
                this.setForm(kh);
            }
        } catch (Exception e) {
            MessageBoxQLCH.alert(this, "Lỗi truy vấn edit");
            throw new RuntimeException();
        }
    }

    void update() {
        KhachHang khModel = getForm();
        try {
            khDao.update(khModel);
            this.fillTable();
            this.clearForm();
            MessageBoxQLCH.alert(this, "Cập nhật khách hàng thành công");
        } catch (Exception e) {
            MessageBoxQLCH.alert(this, "Lỗi cập nhật khách hàng");
            e.printStackTrace();
        }
    }

    void delete() {
        if (!AuthRoleQLCH.isManager()) {
            MessageBoxQLCH.alert(this, "Bạn không có quyền xóa khách hàng");
        } else {
            if (MessageBoxQLCH.confirm(this, "Bạn có muốn xóa Khách hàng này")) {
                String maKH = txtMaKH.getText();
                try {
                    khDao.delete(maKH);
                    this.fillTable();
                    this.clearForm();
                    MessageBoxQLCH.alert(this, "Xóa khách hàng thành công");
                } catch (Exception e) {
                    MessageBoxQLCH.alert(this, "Lỗi xóa khách hàng");
                    e.printStackTrace();
                }
            }
        }
    }

    void TimKiem() {
        this.fillTable();
        this.clearForm();
        this.row = -1;
    }

    @Override
    public void formRefresh() {
    }

}
