/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLCH.UI;

import QLCH.Utils.Masterfrom;
import QLCH.Dao.LoaiSanPhamDao;
import QLCH.Dao.SanPhamDao;
import QLCH.Entity.LoaiSanPham;
import QLCH.Entity.SanPham;
import QLCH.Utils.AuthRoleQLCH;
import QLCH.Utils.MessageBoxQLCH;
import QLCH.Utils.XImageQLCH;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AD
 */
public class SanPhamJPanel extends Masterfrom {

    /**
     * Creates new form SanPhamJPanel
     */
    public SanPhamJPanel() {
        initComponents();
        init();

        tblSanpham1.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 14));
        tblSanpham1.getTableHeader().setBackground(new Color(24, 71, 133));
        tblSanpham1.getTableHeader().setForeground(new Color(255, 255, 255));

        tblDanhmucSP.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 14));
        tblDanhmucSP.getTableHeader().setBackground(new Color(24, 71, 133));
        tblDanhmucSP.getTableHeader().setForeground(new Color(255, 255, 255));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackgroudFormSP = new javax.swing.JPanel();
        tblPanelSanpham = new javax.swing.JTabbedPane();
        pnlSanpham = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanpham1 = new javax.swing.JTable();
        lblAnh = new javax.swing.JLabel();
        lblMaSP = new javax.swing.JLabel();
        lblTenSP = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        lblTenSPTKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        cboSearchTrangThai = new javax.swing.JComboBox<>();
        lblLocLoaiSP = new javax.swing.JLabel();
        lblLoaiSP = new javax.swing.JLabel();
        lblTrangthai = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        txtTrangThai = new javax.swing.JTextField();
        txtGiaSP = new javax.swing.JTextField();
        pnlButton = new javax.swing.JPanel();
        btnThemSP = new javax.swing.JButton();
        btnSuaSP = new javax.swing.JButton();
        btnXoaSP = new javax.swing.JButton();
        btnLammoiSP1 = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnChonAnh = new javax.swing.JButton();
        btnTimkiem = new javax.swing.JButton();
        txtTenSP = new javax.swing.JTextField();
        txtLoaiSanPham = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        lblSoLuong = new javax.swing.JLabel();
        pnlDanhmucSP = new javax.swing.JPanel();
        pnlNhapsolieu = new javax.swing.JPanel();
        lblMaloai = new javax.swing.JLabel();
        txtMaloaiSP = new javax.swing.JTextField();
        lblMaNV = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        lblTenloaiSP = new javax.swing.JLabel();
        txtTenloaiSP = new javax.swing.JTextField();
        btnThemLoai = new javax.swing.JButton();
        btnSuaLoai = new javax.swing.JButton();
        btnXoaLoai = new javax.swing.JButton();
        btnLammoiLoai = new javax.swing.JButton();
        cboLoaiSanPham = new javax.swing.JComboBox<>();
        lblLoaiSanPhamDMSP = new javax.swing.JLabel();
        pnlDanhMucSP = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDanhmucSP = new javax.swing.JTable();

        setBackground(new Color (0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1317, 760));

        pnlBackgroudFormSP.setBackground(new Color (0, 0, 0, 0));

        tblPanelSanpham.setBackground(new Color (0, 0, 0, 0));
        tblPanelSanpham.setForeground(new java.awt.Color(102, 0, 51));
        tblPanelSanpham.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        pnlSanpham.setBackground(new Color (0, 0, 0, 0));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblSanpham1.setAutoCreateRowSorter(true);
        tblSanpham1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblSanpham1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá sản phẩm", "Trạng thái", "Ảnh", "Loại sản phẩm", "Số Lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanpham1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblSanpham1.setOpaque(false);
        tblSanpham1.setRowHeight(23);
        tblSanpham1.getTableHeader().setReorderingAllowed(false);
        tblSanpham1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanpham1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanpham1);

        lblAnh.setBackground(new java.awt.Color(255, 255, 255));
        lblAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new Color (16,54,103), 2));

        lblMaSP.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblMaSP.setForeground(new Color (16,54,103) );
        lblMaSP.setText("Mã sản phẩm");

        lblTenSP.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTenSP.setForeground(new Color (16,54,103) );
        lblTenSP.setText("Tên sản phẩm");

        lblGia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblGia.setForeground(new Color (16,54,103) );
        lblGia.setText("Giá");

        lblTenSPTKiem.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTenSPTKiem.setForeground(new Color (16,54,103) );
        lblTenSPTKiem.setText("Mã sản phẩm");

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimKiem.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 51, 51)));
        txtTimKiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimKiemCaretUpdate(evt);
            }
        });

        cboSearchTrangThai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboSearchTrangThai.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new Color (24, 71, 133)));
        cboSearchTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSearchTrangThaiActionPerformed(evt);
            }
        });

        lblLocLoaiSP.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblLocLoaiSP.setForeground(new Color (16,54,103) );
        lblLocLoaiSP.setText("Loại Sản phẩm");

        lblLoaiSP.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblLoaiSP.setForeground(new Color (16,54,103) );
        lblLoaiSP.setText("Loại sản phẩm");

        lblTrangthai.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTrangthai.setForeground(new Color (16,54,103) );
        lblTrangthai.setText("Trạng thái ");

        txtMaSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTrangThai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtGiaSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGiaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaSPActionPerformed(evt);
            }
        });

        pnlButton.setBackground(new Color (0, 0, 0, 0));

        btnThemSP.setBackground(new Color (24, 71, 133));
        btnThemSP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-plus-48.png"))); // NOI18N
        btnThemSP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnThemSP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPActionPerformed(evt);
            }
        });

        btnSuaSP.setBackground(new Color (24, 71, 133));
        btnSuaSP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSuaSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-edit-48.png"))); // NOI18N
        btnSuaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaSPActionPerformed(evt);
            }
        });

        btnXoaSP.setBackground(new Color (24, 71, 133));
        btnXoaSP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-remove-48.png"))); // NOI18N
        btnXoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSPActionPerformed(evt);
            }
        });

        btnLammoiSP1.setBackground(new Color (24, 71, 133));
        btnLammoiSP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLammoiSP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-add-to-favorites-48.png"))); // NOI18N
        btnLammoiSP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiSP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonLayout = new javax.swing.GroupLayout(pnlButton);
        pnlButton.setLayout(pnlButtonLayout);
        pnlButtonLayout.setHorizontalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLammoiSP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlButtonLayout.createSequentialGroup()
                        .addGroup(pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnXoaSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(btnSuaSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThemSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlButtonLayout.setVerticalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonLayout.createSequentialGroup()
                .addComponent(btnThemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLammoiSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnFirst.setBackground(new Color (24, 71, 133));
        btnFirst.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFirst.setForeground(new java.awt.Color(255, 255, 255));
        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrev.setBackground(new Color (24, 71, 133));
        btnPrev.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(255, 255, 255));
        btnPrev.setText("<<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setBackground(new Color (24, 71, 133));
        btnNext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setBackground(new Color (24, 71, 133));
        btnLast.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLast.setForeground(new java.awt.Color(255, 255, 255));
        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnChonAnh.setBackground(new Color (24, 71, 133));
        btnChonAnh.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnChonAnh.setForeground(new java.awt.Color(255, 255, 255));
        btnChonAnh.setText("Chọn ảnh");
        btnChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhActionPerformed(evt);
            }
        });

        btnTimkiem.setBackground(new Color (24, 71, 133));
        btnTimkiem.setForeground(new java.awt.Color(51, 51, 51));
        btnTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-search-32.png"))); // NOI18N
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        txtTenSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtLoaiSanPham.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblSoLuong.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblSoLuong.setForeground(new Color (16,54,103) );
        lblSoLuong.setText("Số lượng");

        javax.swing.GroupLayout pnlSanphamLayout = new javax.swing.GroupLayout(pnlSanpham);
        pnlSanpham.setLayout(pnlSanphamLayout);
        pnlSanphamLayout.setHorizontalGroup(
            pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSanphamLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSanphamLayout.createSequentialGroup()
                        .addGroup(pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSanphamLayout.createSequentialGroup()
                                .addGroup(pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTenSPTKiem))
                                .addGap(18, 18, 18)
                                .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboSearchTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLocLoaiSP))))
                        .addGap(50, 50, 50))
                    .addGroup(pnlSanphamLayout.createSequentialGroup()
                        .addGroup(pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSanphamLayout.createSequentialGroup()
                                .addGap(387, 387, 387)
                                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlSanphamLayout.createSequentialGroup()
                                .addGroup(pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlSanphamLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                        .addGroup(pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblGia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTenSP)
                                            .addComponent(txtMaSP)
                                            .addComponent(txtGiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(66, 66, 66))
                                    .addGroup(pnlSanphamLayout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(btnChonAnh)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblLoaiSP)
                                    .addComponent(lblTrangthai)
                                    .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLoaiSanPham)
                                    .addComponent(txtTrangThai)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(96, 96, 96)))
                        .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        pnlSanphamLayout.setVerticalGroup(
            pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSanphamLayout.createSequentialGroup()
                .addGroup(pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSanphamLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblLocLoaiSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboSearchTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSanphamLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTimkiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSanphamLayout.createSequentialGroup()
                                .addComponent(lblTenSPTKiem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSanphamLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSanphamLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSanphamLayout.createSequentialGroup()
                                .addGroup(pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTenSP)
                                    .addComponent(lblTrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGia)
                                    .addComponent(lblSoLuong))
                                .addGap(15, 15, 15)
                                .addGroup(pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlSanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnLast)
                                    .addComponent(btnNext)
                                    .addComponent(btnPrev)
                                    .addComponent(btnFirst))
                                .addGap(21, 21, 21))
                            .addGroup(pnlSanphamLayout.createSequentialGroup()
                                .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(19, Short.MAX_VALUE))))))
        );

        tblPanelSanpham.addTab("Sản Phẩm", pnlSanpham);

        pnlDanhmucSP.setBackground(new Color (0, 0, 0, 0));

        pnlNhapsolieu.setBackground(new java.awt.Color(255, 255, 255));
        pnlNhapsolieu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMaloai.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblMaloai.setForeground(new Color (16,54,103));
        lblMaloai.setText("Mã loại sản phẩm");

        txtMaloaiSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblMaNV.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblMaNV.setForeground(new Color (16,54,103));
        lblMaNV.setText("Mã nhân viên");

        txtMaNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblTenloaiSP.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTenloaiSP.setForeground(new Color (16,54,103));
        lblTenloaiSP.setText("Tên loại sản phẩm");

        txtTenloaiSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnThemLoai.setBackground(new Color (24, 71, 133));
        btnThemLoai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-plus-48.png"))); // NOI18N
        btnThemLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLoaiActionPerformed(evt);
            }
        });

        btnSuaLoai.setBackground(new Color (24, 71, 133));
        btnSuaLoai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSuaLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-edit-48.png"))); // NOI18N
        btnSuaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaLoaiActionPerformed(evt);
            }
        });

        btnXoaLoai.setBackground(new Color (24, 71, 133));
        btnXoaLoai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaLoai.setForeground(new java.awt.Color(0, 51, 153));
        btnXoaLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-remove-48.png"))); // NOI18N
        btnXoaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLoaiActionPerformed(evt);
            }
        });

        btnLammoiLoai.setBackground(new Color (24, 71, 133));
        btnLammoiLoai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLammoiLoai.setForeground(new java.awt.Color(0, 51, 153));
        btnLammoiLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/icons8-add-to-favorites-48.png"))); // NOI18N
        btnLammoiLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiLoaiActionPerformed(evt);
            }
        });

        cboLoaiSanPham.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboLoaiSanPham.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new Color (24, 71, 133)));
        cboLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiSanPhamActionPerformed(evt);
            }
        });

        lblLoaiSanPhamDMSP.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblLoaiSanPhamDMSP.setForeground(new Color (16,54,103));
        lblLoaiSanPhamDMSP.setText("Loại sản phẩm");

        javax.swing.GroupLayout pnlNhapsolieuLayout = new javax.swing.GroupLayout(pnlNhapsolieu);
        pnlNhapsolieu.setLayout(pnlNhapsolieuLayout);
        pnlNhapsolieuLayout.setHorizontalGroup(
            pnlNhapsolieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhapsolieuLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnlNhapsolieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlNhapsolieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblLoaiSanPhamDMSP)
                        .addComponent(txtTenloaiSP, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblMaloai)
                        .addComponent(lblMaNV)
                        .addComponent(lblTenloaiSP)
                        .addComponent(cboLoaiSanPham, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMaloaiSP)
                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNhapsolieuLayout.createSequentialGroup()
                        .addGroup(pnlNhapsolieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThemLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(pnlNhapsolieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSuaLoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLammoiLoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pnlNhapsolieuLayout.setVerticalGroup(
            pnlNhapsolieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhapsolieuLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblLoaiSanPhamDMSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(lblMaloai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaloaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMaNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTenloaiSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenloaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(pnlNhapsolieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThemLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlNhapsolieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLammoiLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pnlDanhMucSP.setBackground(new java.awt.Color(255, 255, 255));
        pnlDanhMucSP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH SÁCH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new Color (33, 21, 81))); // NOI18N
        pnlDanhMucSP.setForeground(new Color (33, 21, 81));

        tblDanhmucSP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblDanhmucSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã loại sản phẩm", "Tên loại", "Người tạo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhmucSP.setGridColor(new java.awt.Color(0, 0, 204));
        tblDanhmucSP.setName(""); // NOI18N
        tblDanhmucSP.setRowHeight(23);
        tblDanhmucSP.setSelectionBackground(new Color (24, 116, 180));
        tblDanhmucSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhmucSPMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDanhmucSP);

        javax.swing.GroupLayout pnlDanhMucSPLayout = new javax.swing.GroupLayout(pnlDanhMucSP);
        pnlDanhMucSP.setLayout(pnlDanhMucSPLayout);
        pnlDanhMucSPLayout.setHorizontalGroup(
            pnlDanhMucSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhMucSPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDanhMucSPLayout.setVerticalGroup(
            pnlDanhMucSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhMucSPLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDanhmucSPLayout = new javax.swing.GroupLayout(pnlDanhmucSP);
        pnlDanhmucSP.setLayout(pnlDanhmucSPLayout);
        pnlDanhmucSPLayout.setHorizontalGroup(
            pnlDanhmucSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhmucSPLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(pnlNhapsolieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(pnlDanhMucSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        pnlDanhmucSPLayout.setVerticalGroup(
            pnlDanhmucSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhmucSPLayout.createSequentialGroup()
                .addGroup(pnlDanhmucSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDanhmucSPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlDanhMucSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDanhmucSPLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(pnlNhapsolieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        tblPanelSanpham.addTab("Danh mục sản phẩm", pnlDanhmucSP);

        javax.swing.GroupLayout pnlBackgroudFormSPLayout = new javax.swing.GroupLayout(pnlBackgroudFormSP);
        pnlBackgroudFormSP.setLayout(pnlBackgroudFormSPLayout);
        pnlBackgroudFormSPLayout.setHorizontalGroup(
            pnlBackgroudFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroudFormSPLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(tblPanelSanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 1238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        pnlBackgroudFormSPLayout.setVerticalGroup(
            pnlBackgroudFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroudFormSPLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(tblPanelSanpham)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackgroudFormSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackgroudFormSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblSanpham1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanpham1MouseClicked
        // TODO add your handling code here:=
        int id = tblSanpham1.rowAtPoint(evt.getPoint());
        String masv = tblSanpham1.getValueAt(id, 0).toString();
        SanPham std = spd.SelectbyID(masv);
        lblAnh.setEnabled(false);
        setForm(std);
    }//GEN-LAST:event_tblSanpham1MouseClicked

    private void cboSearchTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSearchTrangThaiActionPerformed
        // TODO add your handling code here:
        chonComBoxSeacher();
    }//GEN-LAST:event_cboSearchTrangThaiActionPerformed

    private void txtGiaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaSPActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaSPActionPerformed

    private void btnThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPActionPerformed
        // TODO add your handling code here:
        insert();
    }//GEN-LAST:event_btnThemSPActionPerformed

    private void btnSuaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaSPActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnSuaSPActionPerformed

    private void btnXoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSPActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnXoaSPActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhActionPerformed
        // TODO add your handling code here:
        chonAnh();
    }//GEN-LAST:event_btnChonAnhActionPerformed

    private void btnThemLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLoaiActionPerformed
        // TODO add your handling code here:
        insertLoaiSanPham();
    }//GEN-LAST:event_btnThemLoaiActionPerformed

    private void btnSuaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaLoaiActionPerformed
        // TODO add your handling code here:
        updateLoaiSanPham();
    }//GEN-LAST:event_btnSuaLoaiActionPerformed

    private void btnXoaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLoaiActionPerformed
        // TODO add your handling code here:
        deleteLoaiSanPham();
    }//GEN-LAST:event_btnXoaLoaiActionPerformed

    private void btnLammoiLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiLoaiActionPerformed
        // TODO add your handling code here:
        clearFormLoaiSanPham();
    }//GEN-LAST:event_btnLammoiLoaiActionPerformed

    private void cboLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiSanPhamActionPerformed
        // TODO add your handling code here:
        chonLoaiSanPham();
    }//GEN-LAST:event_cboLoaiSanPhamActionPerformed

    private void tblDanhmucSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhmucSPMouseClicked
        // TODO add your handling code here:
        int id = tblDanhmucSP.rowAtPoint(evt.getPoint());
        String masv = tblDanhmucSP.getValueAt(id, 0).toString();
        LoaiSanPham lspd = this.lsp.SelectbyID(masv);
        setFormLoaiSanPham(lspd);
    }//GEN-LAST:event_tblDanhmucSPMouseClicked

    private void txtTimKiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimKiemCaretUpdate
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTimKiemCaretUpdate

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        TimKiemSP();
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void btnLammoiSP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiSP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLammoiSP1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLammoiLoai;
    private javax.swing.JButton btnLammoiSP1;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSuaLoai;
    private javax.swing.JButton btnSuaSP;
    private javax.swing.JButton btnThemLoai;
    private javax.swing.JButton btnThemSP;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoaLoai;
    private javax.swing.JButton btnXoaSP;
    private javax.swing.JComboBox<String> cboLoaiSanPham;
    private javax.swing.JComboBox<String> cboSearchTrangThai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblLoaiSP;
    private javax.swing.JLabel lblLoaiSanPhamDMSP;
    private javax.swing.JLabel lblLocLoaiSP;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblMaloai;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblTenSPTKiem;
    private javax.swing.JLabel lblTenloaiSP;
    private javax.swing.JLabel lblTrangthai;
    private javax.swing.JPanel pnlBackgroudFormSP;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlDanhMucSP;
    private javax.swing.JPanel pnlDanhmucSP;
    private javax.swing.JPanel pnlNhapsolieu;
    private javax.swing.JPanel pnlSanpham;
    private javax.swing.JTable tblDanhmucSP;
    private javax.swing.JTabbedPane tblPanelSanpham;
    private javax.swing.JTable tblSanpham1;
    private javax.swing.JTextField txtGiaSP;
    private javax.swing.JTextField txtLoaiSanPham;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtMaloaiSP;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTenloaiSP;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables

    SanPhamDao spd = new SanPhamDao();
    LoaiSanPhamDao lsp = new LoaiSanPhamDao();

    private void init() {
//        this.setLocationRelativeTo(null);
        txtMaNV.setEditable(false);
        fillComBoxSeacherLoaiSanPham();
        fillDanhMucSanPham();
        fillComBoxLoaiSanPham();
    }

    private void fillComBoxSeacherLoaiSanPham() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboSearchTrangThai.getModel();
        model.removeAllElements();
        List<LoaiSanPham> list = lsp.selectAll();
        for (LoaiSanPham cd : list) {
            model.addElement(cd);
        }
    }

    private void fillTableSanPham() {
        DefaultTableModel model = (DefaultTableModel) tblSanpham1.getModel();
        model.setRowCount(0);
        try {
            LoaiSanPham lsp = (LoaiSanPham) cboSearchTrangThai.getSelectedItem();
            List<SanPham> list = spd.selectBySanPham(lsp.getMaLoaiSP());
            for (SanPham sp : list) {
                Object[] row = {
                    sp.getMaSP(),
                    sp.getTenSP(),
                    sp.getGia(),
                    sp.getTrangThai(),
                    sp.getAnh(),
                    sp.getMaLoai(),
                    sp.getSoLuong()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MessageBoxQLCH.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    private void chonComBoxSeacher() {
        LoaiSanPham lsp = (LoaiSanPham) cboSearchTrangThai.getSelectedItem();
        if (lsp != null) {
            fillTableSanPham();
        }
    }

    private void fillComBoxLoaiSanPham() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLoaiSanPham.getModel();
        model.removeAllElements();
        List<LoaiSanPham> list = lsp.selectAll();
        for (LoaiSanPham cd : list) {
            model.addElement(cd);
        }
    }

    JFileChooser fileChooser = new JFileChooser();
    String strhinhAnh;

    private void chonAnh() {
        try {
            JFileChooser jfc = new JFileChooser("E:\\JAVA\\JAVA3\\Hinh");
            jfc.showOpenDialog(null);
            File file = jfc.getSelectedFile();
            Image img = ImageIO.read(file);
            strhinhAnh = file.getName();
            lblAnh.setText(strhinhAnh);
            int width = lblAnh.getWidth();
            int height = lblAnh.getHeight();
            lblAnh.setIcon(new ImageIcon(img.getScaledInstance(width, height, 0)));
            XImageQLCH.save(file);
        } catch (Exception E) {
            System.out.println("erro: " + E.toString());
        }
    }

    private void setForm(SanPham sp) {
        txtLoaiSanPham.setText(sp.getMaLoai());
        txtMaSP.setText(sp.getMaSP());
        txtTenSP.setText(sp.getTenSP());
        txtGiaSP.setText(String.valueOf(sp.getGia()));
        txtTrangThai.setText(sp.getTrangThai());
        txtSoLuong.setText(String.valueOf(sp.getSoLuong()));
        // xu li load hinh anh
        if (sp.getAnh() == null) {
            lblAnh.setText("no image");
            lblAnh.setIcon(null);
        } else {
            ImageIcon img = XImageQLCH.read(sp.getAnh());
            lblAnh.setText(sp.getAnh());
            lblAnh.setToolTipText(sp.getAnh());
            lblAnh.setIcon(XImageQLCH.read(sp.getAnh()));
        }
    }

    private SanPham getForm() {
        SanPham cd = new SanPham();
        cd.setMaLoai(txtLoaiSanPham.getText());
        cd.setMaSP(txtMaSP.getText());
        cd.setTenSP(txtTenSP.getText());
        cd.setGia(Float.valueOf(txtGiaSP.getText()));
        cd.setTrangThai(txtTrangThai.getText());
        cd.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
//        cd.setAnh(lblAnh.getToolTipText());
        if (strhinhAnh == null) {
            cd.setAnh("NULL");
        } else {
            cd.setAnh(strhinhAnh);
        }
        cd.setAnh(lblAnh.getText());
        cd.setAnh(strhinhAnh);
        return cd;
    }

    private void insert() {
        SanPham cd = getForm();
        try {
            spd.insert(cd);
            this.fillTableSanPham();
            MessageBoxQLCH.alert(this, "Thêm mới thành công");
        } catch (Exception e) {
            MessageBoxQLCH.alert(this, "Thêm mới thất bại");
            e.printStackTrace();
        }
    }

    private void update() {
        SanPham kh = getForm();
        try {
            spd.update(kh);
            this.fillTableSanPham();
            clearForm();
            MessageBoxQLCH.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            MessageBoxQLCH.alert(pnlBackgroudFormSP, "Cập nhật thất bại!");
        }
    }

    private void delete() {
        try {
            String cd = txtMaSP.getText();
            spd.delete(cd);
            this.fillTableSanPham();
            this.clearForm();
            MessageBoxQLCH.alert(this, "Xóa thành công!");
        } catch (Exception e) {
            MessageBoxQLCH.alert(this, "Xóa thất bại!");
            e.printStackTrace();
        }
    }

    private void first() {
        this.row = 0;
        this.edit();
    }

    private void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    private void next() {
        if (this.row < tblSanpham1.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }

    private void last() {
        this.row = tblSanpham1.getRowCount() - 1;
        this.edit();
    }

    private void clearForm() {
        SanPham cd = new SanPham();
        this.setForm(cd);
        this.row = -1;
        lblAnh.setText("");
        lblAnh.setIcon(null);
    }

    private int row = -1;

    private void edit() {
        String macd = (String) tblSanpham1.getValueAt(this.row, 0);
        SanPham cd = spd.SelectbyID(macd);
        this.setForm(cd);
    }

    private void fillDanhMucSanPham() {
        DefaultTableModel model = (DefaultTableModel) tblDanhmucSP.getModel();
        model.setRowCount(0);
        try {
            List<LoaiSanPham> list = lsp.selectAll();
            for (LoaiSanPham lsp : list) {
                Object[] row = {
                    lsp.getMaLoaiSP(),
                    lsp.getTenLoai(),
                    lsp.getMaNV(),};
                model.addRow(row);
            }
        } catch (Exception e) {
            MessageBoxQLCH.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    private void setFormLoaiSanPham(LoaiSanPham lsp) {
        txtMaloaiSP.setText(lsp.getMaLoaiSP());
        txtMaNV.setText(lsp.getMaNV());
        txtTenloaiSP.setText(lsp.getTenLoai());
    }

    private LoaiSanPham getFormLoaiSanPham() {
        LoaiSanPham lsp = new LoaiSanPham();
        lsp.setMaLoaiSP(txtMaloaiSP.getText());
        lsp.setMaNV(txtMaNV.getText());
        lsp.setTenLoai(txtTenloaiSP.getText());
        return lsp;
    }

    private void chonLoaiSanPham() {
        LoaiSanPham lsp = (LoaiSanPham) cboLoaiSanPham.getSelectedItem();
        if (lsp != null) {
            setFormLoaiSanPham(lsp);
        }
    }

    private void insertLoaiSanPham() {
        LoaiSanPham cd = getFormLoaiSanPham();
        try {
            lsp.insert(cd);
            fillComBoxSeacherLoaiSanPham();
            fillDanhMucSanPham();
            fillComBoxLoaiSanPham();
            MessageBoxQLCH.alert(this, "Thêm mới thành công");
        } catch (Exception e) {
            MessageBoxQLCH.alert(this, "Thêm mới thất bại");
            e.printStackTrace();
        }
    }

    private void deleteLoaiSanPham() {
        try {
            String cd = txtMaloaiSP.getText();
            lsp.delete(cd);
            fillComBoxSeacherLoaiSanPham();
            fillDanhMucSanPham();
            fillComBoxLoaiSanPham();
//                    this.clearForm();
            MessageBoxQLCH.alert(this, "Xóa thành công!");
        } catch (Exception e) {
            MessageBoxQLCH.alert(this, "Xóa thất bại!");
            e.printStackTrace();
        }
    }

    private void updateLoaiSanPham() {
        LoaiSanPham kh = getFormLoaiSanPham();
        try {
            lsp.update(kh);
            fillComBoxSeacherLoaiSanPham();
            fillDanhMucSanPham();
            fillComBoxLoaiSanPham();

            MessageBoxQLCH.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            MessageBoxQLCH.alert(pnlBackgroudFormSP, "Cập nhật thất bại!");
        }
    }

    private void clearFormLoaiSanPham() {
        LoaiSanPham cd = new LoaiSanPham();
        this.setFormLoaiSanPham(cd);
        txtMaNV.setText(AuthRoleQLCH.user.getMaNV());
        this.row = -1;
    }

    @Override
    public void formRefresh() {
    }
    
    private void TimKiemSP(){
        DefaultTableModel model = (DefaultTableModel) tblSanpham1.getModel();
        model.setRowCount(0);
        try{
            LoaiSanPham lsp = (LoaiSanPham)cboSearchTrangThai.getSelectedItem();
        String keyword = txtTimKiem.getText();
        List<SanPham> list = spd.selectNotInCouse(lsp.getMaLoaiSP(), keyword);
            for(SanPham sp : list){
                Object[] row = {
                    sp.getMaSP(),
                    sp.getTenSP(),
                    sp.getGia(),
                    sp.getTrangThai(),
                    sp.getAnh(),
                    sp.getMaLoai()
                    };
                model.addRow(row);
            }        
        }catch(Exception e){
            MessageBoxQLCH.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }
}
