/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLCH.UI;
import QLCH.Utils.Masterfrom;
import javax.swing.ImageIcon;
import AppPackage.AnimationClass;
import QLCH.Utils.AuthRoleQLCH;

/**
 *
 * @author AD
 */
public class TrangChuJPanel extends Masterfrom {

    AnimationClass ac = new AnimationClass();

    /**
     * Creates new form TrangChuJPanel
     */
    public TrangChuJPanel() {
        initComponents();
        showAnimation();
    }

    public void showAnimation() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                int nb = 0;
                try {
                    while (true) {
                        switch (nb) {
                            case 0:
                                Thread.sleep(1500);
                                ac.jLabelXLeft(0, -500, 12, 10, img3);
                                ac.jLabelXLeft(500, 0, 12, 10, img2);
                                ac.jLabelXLeft(1000, 500, 12, 10, img1);
                                nb++;
                            case 1:
                                Thread.sleep(1500);
                                ac.jLabelXLeft(-500, -1000, 12, 10, img3);
                                ac.jLabelXLeft(0, -500, 12, 10, img2);
                                ac.jLabelXLeft(500, 0, 12, 10, img1);
                                nb++;
                            case 2:
                                Thread.sleep(1500);
                                ac.jLabelXRight(-1000, -500, 12, 10, img3);
                                ac.jLabelXRight(-500, 0, 12, 10, img2);
                                ac.jLabelXRight(0, 500, 12, 10, img1);
                                nb++;
                            case 3:
                                Thread.sleep(1500);
                                ac.jLabelXRight(-500, 0, 12, 10, img3);
                                ac.jLabelXRight(0, 500, 12, 10, img2);
                                ac.jLabelXRight(500, 1000, 12, 10, img1);
                                nb = 0;
                        }
                    }
                } catch (Exception e) {
                }
            }

        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        pnlSildePicture = new javax.swing.JPanel();
        img3 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        pnlPicture = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        pnlContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSildePicture.setBackground(new java.awt.Color(255, 255, 255));
        pnlSildePicture.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/SlidePc1.jpg"))); // NOI18N
        img3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        img3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlSildePicture.add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        img2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/SlidePc2.jpg"))); // NOI18N
        img2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        img2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlSildePicture.add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        img1.setBackground(new java.awt.Color(255, 255, 255));
        img1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/trasua.jpg"))); // NOI18N
        img1.setText("       ");
        img1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        img1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlSildePicture.add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        pnlContainer.add(pnlSildePicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 42, 400, 400));

        pnlPicture.setBackground(new java.awt.Color(102, 255, 102));
        pnlPicture.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/YummyJava.png"))); // NOI18N
        pnlPicture.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 290));

        pnlContainer.add(pnlPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 1320, 290));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCH/Icon/Previous work1.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlContainer.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 800, 440));

        add(pnlContainer, "card2");
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void formRefresh() {
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlPicture;
    private javax.swing.JPanel pnlSildePicture;
    // End of variables declaration//GEN-END:variables

}
